kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheudler-role
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheudler-rolebinding
  namespace: scheduler-example
subjects:
  - kind: ServiceAccount
    name: default
    namespace: scheduler-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheudler-role